version: '3.9'
services:
  cacttus-core-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=burgu
      - POSTGRES_PASSWORD=burgu
      - POSTGRES_DB=burguDB
    ports:
      - '5432:5432'